### ISSUE TITLE
graphqlLoaderPlugin is not a function

### ISSUE THREAD

**Issue by ghost** [luckycatfactory/esbuild-graphql-loader#20]
```
    plugins: [graphqlLoaderPlugin()],
              ^

TypeError: graphqlLoaderPlugin is not a function
```
Trying to use your example but I'm somehow getting this error.

**Comment by bennypowers** [comment]
`graphqlLoaderPlugin.default()` should work

**Comment by louisscruz** [comment]
I believe @bennypowers has answer this. Closing.

**Comment by bennypowers** [comment]
to be clear, my comment is a workaround. I think this library should use module exports to point to cjs and esm versions

**Comment by ejkg** [comment]
Although this solution works it gives a typescript error
```
Property 'default' does not exist on type '(options?: GraphQLLoaderPluginOptions) => Plugin'.ts(2339)
```

**Comment by jacob-orbiit** [comment]
This problem is easily fixed properly as Bennypowers describes, and the usage example currently in the README is wrong as the package currently stands (`plugins: [graphqlLoaderPlugin()]` instead of `plugins: [graphqlLoaderPlugin.default()],`).

**Comment by jschuur** [comment]
> This problem is easily fixed properly as Bennypowers describes, and the usage example currently in the README is wrong as the package currently stands (`plugins: [graphqlLoaderPlugin()]` instead of `plugins: [graphqlLoaderPlugin.default()],`).

Yep. I was stumped until I found this issue, because I followed the README instructions.
