### ISSUE TITLE
FYI: This has been added to the esbuild plugin list

### ISSUE THREAD

**Issue by evanw** [luckycatfactory/esbuild-graphql-loader#9]
I recently started a repo with a list of links to esbuild plugins so other people can find them. And I just merged a PR to add this plugin to the list of esbuild plugins: https://github.com/esbuild/community-plugins/pull/3.

However, I realized after merging the PR that the person who filed the PR may not be the package author. If that's the case, please confirm that you want your plugin on this list and that the description is what you want it to be. I'm happy to change the description or remove the package if you'd prefer for it to not be on the list.

Sorry about the oversight.

**Comment by louisscruz** [comment]
Fantastic! I am the author, and I'm very glad to see this on the list. Thanks a ton.
